name: 'Hello World'
on: 
  push:
    branches: [master]


jobs:
  ci_to_master: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      run: npm ci
      run: npm test
      run: npm run build
