name: push on main
on:
   pull_request_review:
    types: 
      - submitted

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Imprimir version del git
      run: |
        git --version
        echo "Path is ... $PATH"
    - name: hacer mezcla del pull request
      run: |
        git checkout master
        git merge develop