name: merge on approve
on:
  pull_request_review:
    types:
      - submitted
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-automerge-action@v1.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
      with:
        merge-method: 'merge' # Default 'squash'
        base-ref: 'master' # Default 'dev'