name: automerge
on:
  pull_request_review:
    types:
      - submitted
jobs:
  automerge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    run: |
      'echo  Pull request FROM "${{ github.event.inputs.pull-request }}"'
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.REPOSITORY_TOKEN }}
          merge-method: rebase
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: false