name: automerge
on:
  pull_request_review:
    types:
      - submitted
jobs:
  automerge:
    if: github.event.review.state == 'approved' || !github.event.review
    runs-on: ubuntu-latest
    steps:
      - name: echo state event
        run: |
            echo "state from event review '${{ github.event.review.state }}'"
             echo "state from event review '${{ !github.event.review }}'"

      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.REPOSITORY_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge
          required-labels: automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: true