name: automerge
on:
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Merge command
      uses: Goobles/gh-actions-merge-command@v1
      with:
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}