name: push on main
on:
   pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      run: echo "esto significa que si imprime la accion"