name: push on main
on:
   pull_request_review:
    types: 
      - submitted

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Imprimir version del git
      run: |
        git --version
        echo "Path is ... $PATH"
    - name: merge
      uses: mtanzi/action-automerge@v1
      id: merge
      with:
        github_token: ${{ github.REPOSITORY_TOKEN}}
        source: 'develop'
        target: 'main'