name: push on main
on:
   pull_request_review:
    types: 
      - submitted

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      run: |
        git --version
        echo "Path is ... $PATH"