name: push on main
on:
   pull_request_review:
    types: 
      - submitted

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Imprimir version del git
      run: |
        git --version
        echo "Path is ... $PATH"
    - name: impresion branches
      run: |
        git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
        git fetch --all
        git checkout main
    - name: merge pull request
      run: |
        git checkout main
        git merge develop